### ISSUE TITLE
Slow startup time for 'from pkg_resources import load_entry_point'

### ISSUE THREAD

**Issue by Russell91** [Russell91/pythonpy#64]
I noticed that using load_entry_point was particularly slow on one server that I used. Running `python -c 'from pkg_resources import load_entry_point'` took 0.325 seconds! That's completely unacceptable. Even calls to `py 3` take 0.325 seconds on that system, when they should take at most `0.05` seconds. I wasn't aware of the potential costs when we switched to entry points for the pip install. They also make newcomers much more fearful of pythonpy's complexity, even though it's just a single python file. I'm interested in migrating back to those simpler times. Does anyone have some warnings about the costs of switching away from entry points?

**Comment by JonathonReinhart** [comment]
Hi Russell, I'm seeing the same issue in my utility (https://github.com/JonathonReinhart/scuba/issues/71). I see you closed this issue, what did you end up doing?
