### ISSUE TITLE
setup.py --root and the bash completion script

### ISSUE THREAD

**Issue by eigengrau** [Russell91/pythonpy#67]
The way setup.py installs the bash completion script is a bit unfortunate when building for a package. Here, we would usually not install as root, and instead set the installation location by using --root="$pkgdir". However, when installing the bash completion script, setup.py currently ignores this and determines the destination path by trying to write to a global path, which fails, and then falls back to no prefix, which would cause the completion script to be installed under /usr/bash_completion.d.

**Comment by eigengrau** [comment]
At least for Archlinux’s makepkg, the packaging step is ran under fakeroot, so special casing UID == 0 would work here. I don’t know about other packaging systems, though. If setuptools exposes the --root setting, you could just prepend this to all paths.

**Comment by Russell91** [comment]
Can you explain the consequences of this more clearly? How important is this to fix?

**Comment by eigengrau** [comment]
With the currenty setup.py, the completion script is not installed properly when a root prefix other than `/` is needed (e. g., when building distro packages). Making setup.py respect the root prefix supplied with the `--root=$DIR` switch from setuptools would allow packaging pythonpy without patching the setup script downstream.

**Comment by McNoggins** [comment]
Here is the list of installed files on Arch Linux using the following build rules: https://aur.archlinux.org/packages/py/python-pythonpy/PKGBUILD. The first four files should go in /etc, not /usr

    python-pythonpy /usr/
    python-pythonpy /usr/bash_completion.d/
    python-pythonpy /usr/bash_completion.d/pycompletion.sh
    python-pythonpy /usr/bin/
    python-pythonpy /usr/bin/py
    python-pythonpy /usr/bin/py3
    python-pythonpy /usr/bin/py3.4
    python-pythonpy /usr/bin/pycompleter
    python-pythonpy /usr/bin/pycompleter3
    python-pythonpy /usr/bin/pycompleter3.4
    python-pythonpy /usr/lib/
    python-pythonpy /usr/lib/python3.4/
    python-pythonpy /usr/lib/python3.4/site-packages/
    python-pythonpy /usr/lib/python3.4/site-packages/pythonpy-0.3.7-py3.4.egg-info/
    python-pythonpy /usr/lib/python3.4/site-packages/pythonpy-0.3.7-py3.4.egg-info/PKG-INFO
    python-pythonpy /usr/lib/python3.4/site-packages/pythonpy-0.3.7-py3.4.egg-info/SOURCES.txt
    python-pythonpy /usr/lib/python3.4/site-packages/pythonpy-0.3.7-py3.4.egg-info/dependency_links.txt
    python-pythonpy /usr/lib/python3.4/site-packages/pythonpy-0.3.7-py3.4.egg-info/entry_points.txt
    python-pythonpy /usr/lib/python3.4/site-packages/pythonpy-0.3.7-py3.4.egg-info/top_level.txt
    python-pythonpy /usr/lib/python3.4/site-packages/pythonpy/
    python-pythonpy /usr/lib/python3.4/site-packages/pythonpy/__init__.py
    python-pythonpy /usr/lib/python3.4/site-packages/pythonpy/__main__.py
    python-pythonpy /usr/lib/python3.4/site-packages/pythonpy/__pycache__/
    python-pythonpy /usr/lib/python3.4/site-packages/pythonpy/__pycache__/__init__.cpython-34.pyc
    python-pythonpy /usr/lib/python3.4/site-packages/pythonpy/__pycache__/__main__.cpython-34.pyc
    python-pythonpy /usr/lib/python3.4/site-    packages/pythonpy/__pycache__/pycompleter.cpython-34.pyc
    python-pythonpy /usr/lib/python3.4/site-packages/pythonpy/pycompleter.py

**Comment by McNoggins** [comment]
I fail to see why this issue was closed.
