### ISSUE TITLE
Option for assigning the whole pipe output a single variable

### ISSUE THREAD

**Issue by alendit** [Russell91/pythonpy#68]
Hi,

suppose I want to download all the images from the frontpage of http://imgur.com

    curl http://imgur.com/ | py -l 'map(lambda _: _.attrs["src"].partition("//")[-1], bs4.BeautifulSoup("\n".join(l)).findAll("img"))' | xargs -n1 wget >/dev/null 2>&1

Right now I have to manually do `"\n".join(l)`. It would be nice, if there would be an option to do it atomatically, like

    curl http://imgur.com/ | py -c 'map(lambda _: _.attrs["src"].partition("//")[-1], bs4.BeautifulSoup(c).findAll("img"))' | xargs -n1 wget >/dev/null 2>&1

i.e. replace `"\n".join(l)` with `c`.

**Comment by Russell91** [comment]
sys.stdin contains a string of standard input, unmodified by pythonpy. So

    curl http://imgur.com/ | py 'map(lambda _: _.attrs["src"].partition("//")[-1], bs4.BeautifulSoup(sys.stdin).findAll("img"))' | xargs -n1 wget >/dev/null 2>&1

should do the trick.

**Comment by alendit** [comment]
Hi,

thanks, I'll close it then.
