### ISSUE TITLE
Automatic import of numerical tools

### ISSUE THREAD

**Issue by MatthieuBizien** [Russell91/pythonpy#71]
It would be wonderful to have the major numerical packages imported automatically.

* import pandas as pd
* import numpy as np
* from pylab import plt
* import seaborn as sns
* from sklearn import linear_model, preprocessing, grid_search, tree, metrics, pipeline, ensemble, cross_validation

If it is too long to import those packages,  I suggest a "-n" ie "--numerical" option that import the major packages.

It would also be nice to convert the input, but I am not sure which behavior should be implemented.

**Comment by Russell91** [comment]
Are you aware that you can say:

    py 'numpy.arange(3)'
    0
    1
    2

**Comment by Russell91** [comment]
numpy and pandas have been addressed in https://github.com/Russell91/pythonpy/commit/12eaa7fb79e6799e94e5255f86d64765589cec4f. I don't think the others are common enough to warrant special exceptions (even pandas was a bit of a stretch). But adding others in the future could make sense.
