### ISSUE TITLE
Tag releases in Git

### ISSUE THREAD

**Issue by myhro** [Russell91/pythonpy#76]
Hi Russel,

I'm packaging this awesome piece of software (thank you for writing it!) as a Debian package (bug [#817856][1]). What do you think about tagging releases in Git? Whenever you finish a new release, besides updating the files that mention its number and uploading to PyPI, you also create a [`git tag`][2] for it.

This way, it would be easier to create a `watch` file that can compare the version that is packaged against (possible) newer releases on this GitHub repository.

Regards,
Tiago.

[1]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=817856
[2]: https://git-scm.com/book/en/v2/Git-Basics-Tagging

**Comment by Russell91** [comment]
I think this is a great idea, but I'm not familiar with how to implement it. Is it something that would be applied retroactively?

**Comment by myhro** [comment]
> Is it something that would be applied retroactively?

From my perspective, if you create a `0.4.9` tag for the current release right now (8246347) and tag every release from now on, would be enough. There's no need to create tags for previous releases.

**Comment by myhro** [comment]
I was able to create a [watch file][1] and properly fetch new versions from the "releases" tab.

Thank you very much, Russel. :-)

[1]: https://github.com/myhro/deb-pythonpy/commit/fdfce108b94ca657966abff8464fd7ede7a5050d
