### ISSUE TITLE
Strange tab-completion behaviour

### ISSUE THREAD

**Issue by myhro** [Russell91/pythonpy#77]
Hi Russel,

I've noticed something funny about the tab-completion. I'm trying to do the following:

    Input: py 'rand<Tab>
    Output: py 'random

    Input: py 'random.cho<Tab>
    Output: py 'random.choice

This is expected. But when I try to complete an argument, like:

    Input: py 'random.choice(string.le<Tab>

It becomes:

    Output: py 'string.letters

Instead of `random.choice(string.letters`.

Do you know how this can be fixed?

Regards,
Tiago.

**Comment by Russell91** [comment]
The primary reason for this is that bash exposes a terrible completion API, and there are a huge number of workarounds in pycompleter to get around this. The core of the problem is that you cannot independently control the printed output effect of hitting tab and the input modification effect of hitting tab. That being said, the behavior you describe should have already been addressed. Can you verify you are using the most recent version?

**Comment by myhro** [comment]
> That being said, the behavior you describe should have already been addressed by only showing the options for tab completion and not changing the input. Is this what is happening for you?

No. Even in this case, if I type `string.<Tab>`, for instance, it will first overwrite the output and then, only on the second `<Tab>`, it will show the options.

**Comment by Russell91** [comment]
Are you using ubuntu?

**Comment by myhro** [comment]
No, Debian. I've tried both on Jessie (bash `4.3.30`) and Sid (bash `4.3.42`) and pythonpy `0.4.9`.

**Comment by Russell91** [comment]
I see, I've only confirmed that it works on bash 4.3.8 and earlier on OSX and Ubuntu. It's possible that they've changed the behavior, although I don't know why they would do that. If you want to play around with it, try writing `pycompleter string.let`, and then look at the shell script found with `find_pycompletion.sh`. The output of pycompleter should be correct, and any difference should be explained by what's going on in pycompletion.sh, which is just a few lines of bash in the _py() function.

**Comment by myhro** [comment]
> I see, I've only confirmed that it works on bash 4.3.8 and earlier on OSX and Ubuntu.

Can you confirm that it work as expected on your computer? I've tested on Ubuntu 14.04 (bash `4.3.11`) and 12.04 (bash `4.2.25`), both with pythonpy `0.4.10`, and the result was the same.

> The output of pycompleter should be correct, and any difference should be explained by what's going on in pycompletion.sh, which is just a few lines of bash in the _py() function.

The output of `pycompleter 'string.le'` and `pycompleter 'random.choice(string.le'` is the same: `string.letters string.letters'`. That's why I'm suspicious that it never worked the way I expected.

**Comment by Russell91** [comment]
Oh, yes! You are indeed seeing the correct behavior then. So, you have to understand how completely abysmal the bash completion API is to understand why pycompleter makes the choices it does. But without the `string.letters'` option in there as you see, what would happen is that bash would rewrite your **input** from `py 'random.choice(string.le'` to `py 'string.letters'`, which is extremely annoying. Note that the current version is annoying... but still provides useful information and doesn't actively fight you. Sorry for the confusion - I thought you were reporting a bug in the rather complicated workarounds.

Suffice it to say that implementing ipython style tab completion is just non-trivial.

**Comment by myhro** [comment]
Thank you very much for the explanation, Russel.

> Suffice it to say that implementing ipython style tab completion inside single quotes on the command line is just non-trivial.

Indeed that is what I was expecting. There's no problem now that I know the limitations. :-)

I'm closing this issue.
