### ISSUE TITLE
Completion doesn't work if python executable refers to another Python version

### ISSUE THREAD

**Issue by remcohaszing** [Russell91/pythonpy#78]
### Environment

I am running Ubuntu 16.04. For Python this means that:

* `python2` refers to Python 2.7
* `python3` refers to Python 3.5
* `python` refers to Python 2.7

I install some handy Python tools, including `pip` itself and `pythonpy`, using the `--user` flag. This installs everything in the `~/.local` prefix (and doesn't require `sudo`). I install those tools using Python 3.5.

```sh
curl https://bootstrap.pypa.io/get-pip.py | python3 - --user
pip install --user pythonpy
```

Note that this is **not** a virtual environment, so it doesn't create another `python` executable.

### Issue

This means I have an environment in which:
- The `python` executable refers to a Python 2.7 environment in which `pythonpy` is not installed.
- The `py` executable refers to a Python 3.5 environment.

The `find_completion.sh` script appears to depend on the `python` executable referring to the environment in which `pythonpy` is installed.
```sh
$ find_pycompletion.sh 
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1151, in resource_filename
    return get_provider(package_or_requirement).get_resource_filename(
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 426, in get_provider
    __import__(moduleOrReq)
ImportError: No module named pythonpy.completion
```

### Potential solutions

Some tools, including `pip`, have a completion command. Instead of sourcing a script, autocomplete can be triggered using:
```sh
$ source <(pip completion --bash)
```

I suppose something similar could be created for `py`.
```sh
$ source <(py completion)
```

Possibly install a completion script to `$prefix/etc/bash_completion.d/` which just runs the command above.

**Comment by Russell91** [comment]
Fair enough. I believe that commit https://github.com/Russell91/pythonpy/commit/f64063d22ff134adee918692a0794da0c2b1db1e should take care of it in version 0.4.11. Can you confirm?

**Comment by remcohaszing** [comment]
Yep this works. Thanks!
